---
replicaCount: 1

image:
  repository: ghcr.io/catenax-ng/product-item-relationship-service-frontend
  pullPolicy: Always
  tag: 1.0.1

serviceAccount:
  create: true
  annotations: {}
  name: ""

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

registry:
  default:
    global:
      asset:
        id:
  vite:
    manual:
      url:
  url:
    local:
keycloak:
  url:
  grand:
    type:
  scope:
  client:
    id:
    secret:

ingress:
  enabled: false